spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orchestrator_db
    username: orchestrator
    password: orchestrator_pass
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: vamshi
      password: vamshi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework: INFO
    com.vamshi.jobOrchestrator: DEBUG

server:
  port: 8080

# Actuator and OpenAPI
management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

